// Normalized categories observed in the consolidated workbook, plus the explicitly
// requested operational fee rule. Broad categories may need several concrete issues.
export const CATEGORY_ISSUE_TYPES = {
    'Name Search':['NAME_SEARCH_MISSING'], 'Typing':['TYPING_ERROR'],
    'Document':['MISSING_DOCUMENT'], 'Document Request':['DOCUMENT_COPY_REQUEST'],
    'Wrong Document':['WRONG_DOCUMENT'], 'Attorney Opinion':['ATTORNEY_OPINION_DISCREPANCY'],
    'Pacer Search':['PACER_SEARCH_DISCREPANCY'], 'Pacer and Patriot':['PACER_SEARCH_DISCREPANCY','PATRIOT_SEARCH_DISCREPANCY'],
    'Patriot':['PATRIOT_SEARCH_DISCREPANCY'], 'Vesting Name':['VESTING_DISCREPANCY'],
    'Comment':['REPORT_COMMENT_DISCREPANCY'], 'Vendor Management Requirement':['VENDOR_REQUIREMENT_DISCREPANCY'],
    'Effective Date':['EFFECTIVE_DATE_DISCREPANCY'], 'Tax / Assessor':['TAX_DISCREPANCY'],
    'Plat Map':['PLAT_MAP_DISCREPANCY'], 'GIS Map':['GIS_MAP_DISCREPANCY'],
    'Chain of Title':['CHAIN_BREAK'], '24 Month Chain':['CHAIN_24_MONTH_DISCREPANCY'],
    'Cost Work Sheet':['COST_WORKSHEET_DISCREPANCY'], 'HOA':['HOA_DISCREPANCY'], 'PUD Comment':['PUD_DISCREPANCY'],
    'Parcel ID':['PARCEL_MISMATCH'], 'Legal Description':['LEGAL_DESCRIPTION_MISMATCH'],
    'Property Report':['PROPERTY_REPORT_DISCREPANCY'], 'Search Package':['SEARCH_PACKAGE_DISCREPANCY'],
    'Address':['ADDRESS_DISCREPANCY'], 'Property Identification':['PROPERTY_IDENTIFICATION'],
    'Mailing List':['MAILING_LIST_DISCREPANCY'],
    'Abstractor':['ATTORNEY_OPINION_DISCREPANCY','ABSTRACTOR_STATUS'],
    'Update Report':['UPDATE_REPORT_DISCREPANCY'], 'Lien Registry':['LIEN_REGISTRY_DISCREPANCY'],
    'Court Search':['COURT_DISCREPANCY'], 'County Change':['COUNTY_DISCREPANCY'],
    'Wrong Order Number':['ORDER_NUMBER_DISCREPANCY'], 'Unofficial Copies':['UNOFFICIAL_COPY_ISSUE'],
    'Index':['INDEX_SEARCH_DISCREPANCY'], 'Water Mark Copies':['WATERMARK_COPY_ISSUE'],
    'Recording Date':['RECORDING_DATE_DISCREPANCY'], 'Judgment':['JUDGMENT_SEARCH_DISCREPANCY'],
    'Lender Name':['LENDER_NAME_DISCREPANCY'], 'Assignment Chain':['ASSIGNMENT_CHAIN_DISCREPANCY'],
    'Mortgage':['MORTGAGE_DISCREPANCY'], 'Survey':['SURVEY_DISCREPANCY'], 'Torrens':['TORRENS_CERTIFICATE_DISCREPANCY'],
    'Cover Sheet':['COVER_SHEET_DISCREPANCY'], 'Marital Status':['MARITAL_STATUS_DISCREPANCY'],
    'Tax Warrant':['TAX_WARRANT_DISCREPANCY'], 'Sunbiz':['SUNBIZ_SEARCH_DISCREPANCY'],
    'No Revision Request':['NO_REVISION_REQUEST'], 'Checklist':['CHECKLIST_DISCREPANCY'], 'THR Report':['THR_DISCREPANCY'],
    'Effective Date / Typing':['EFFECTIVE_DATE_DISCREPANCY','TYPING_ERROR'],
    'Abstractor / Typing':['ATTORNEY_OPINION_DISCREPANCY','TYPING_ERROR'],
    'Fee Approval':['FEE_APPROVAL_REQUEST']
};
