/**
 * Phase 2 Document Registry and Rule-Based Issue-to-Document Mappings.
 * Ensures Gemini strictly targets relevant document types for evidence extraction.
 */

export const DOCUMENT_TYPES = [
    "SEARCH_PACKAGE",
    "DEED",
    "DOT",
    "TAX",
    "PA",
    "LEGAL_DESCRIPTION",
    "MAP",
    "LIEN",
    "PACER",
    "PATRIOT",
    "TYPED_REPORT",
    "COST_WORKSHEET",
    "THR",
    "INDEX", "ATTORNEY_OPINION", "VENDOR_INSTRUCTIONS", "HOA_DOCUMENT", "MAILING_LIST",
    "PROPERTY_REPORT", "UPDATE_REPORT", "LIEN_REGISTRY", "COURT_SEARCH", "PROBATE",
    "SURVEY", "TORRENS", "COVER_SHEET", "CHECKLIST", "SUNBIZ", "ASSIGNMENT"
];

export const DOCUMENT_MAPPINGS = {
    MISSING_DEED: ["DEED", "SEARCH_PACKAGE", "TYPED_REPORT"],
    CHAIN_BREAK: ["SEARCH_PACKAGE", "DEED", "TYPED_REPORT"],
    PARCEL_MISMATCH: ["TAX", "PA", "SEARCH_PACKAGE", "LEGAL_DESCRIPTION", "MAP"],
    LEGAL_DESCRIPTION_MISMATCH: ["LEGAL_DESCRIPTION", "DEED", "DOT", "PA", "SEARCH_PACKAGE", "MAP"],
    TYPING_ERROR: ["TYPED_REPORT", "SEARCH_PACKAGE", "DEED"],
    TAX_DISCREPANCY: ["TAX", "TYPED_REPORT"],
    LIEN_DISCREPANCY: ["LIEN", "SEARCH_PACKAGE", "TYPED_REPORT"],
    COURT_DISCREPANCY: ["TYPED_REPORT", "SEARCH_PACKAGE", "LIEN", "COURT_SEARCH"],
    BANKRUPTCY_DISCREPANCY: ["PACER", "PATRIOT", "TYPED_REPORT", "SEARCH_PACKAGE"],
    VESTING_DISCREPANCY: ["SEARCH_PACKAGE", "DEED", "TYPED_REPORT", "TA"],
    DEED_DISCREPANCY: ["DEED", "SEARCH_PACKAGE", "TYPED_REPORT"],
    NAME_SEARCH_MISSING: ["PACER", "PATRIOT", "TYPED_REPORT", "SEARCH_PACKAGE", "INDEX"],
    SEARCH_DEPTH: ["SEARCH_PACKAGE", "DEED", "TYPED_REPORT", "TA"],
    MISSING_DOCUMENT: ["SEARCH_PACKAGE", "DEED", "THR", "TYPED_REPORT"],
    MORTGAGE_DISCREPANCY: ["DOT", "SEARCH_PACKAGE", "TYPED_REPORT", "THR"],
    PROPERTY_IDENTIFICATION: ["TAX", "PA", "LEGAL_DESCRIPTION", "MAP", "SEARCH_PACKAGE"],
    LEASEHOLD_DISCREPANCY: ["DEED", "LEGAL_DESCRIPTION", "SEARCH_PACKAGE", "TYPED_REPORT"],
    ATTORNEY_OPINION_DISCREPANCY: ["ATTORNEY_OPINION", "SEARCH_PACKAGE", "TYPED_REPORT"],
    VENDOR_REQUIREMENT_DISCREPANCY: ["VENDOR_INSTRUCTIONS", "SEARCH_PACKAGE", "TYPED_REPORT"],
    EFFECTIVE_DATE_DISCREPANCY: ["INDEX", "SEARCH_PACKAGE", "TYPED_REPORT"],
    RECORDING_DATE_DISCREPANCY: ["SEARCH_PACKAGE", "TYPED_REPORT"],
    EXECUTION_DATE_DISCREPANCY: ["SEARCH_PACKAGE", "TYPED_REPORT"],
    COST_WORKSHEET_DISCREPANCY: ["COST_WORKSHEET", "VENDOR_INSTRUCTIONS"],
    HOA_DISCREPANCY: ["SEARCH_PACKAGE", "TYPED_REPORT", "HOA_DOCUMENT"],
    PUD_DISCREPANCY: ["DOT", "SEARCH_PACKAGE", "TYPED_REPORT"],
    PLAT_MAP_DISCREPANCY: ["MAP", "LEGAL_DESCRIPTION", "SEARCH_PACKAGE"],
    GIS_MAP_DISCREPANCY: ["MAP", "PA", "SEARCH_PACKAGE"],
    PROPERTY_REPORT_DISCREPANCY: ["PROPERTY_REPORT", "SEARCH_PACKAGE", "TYPED_REPORT"],
    SEARCH_PACKAGE_DISCREPANCY: ["SEARCH_PACKAGE", "TYPED_REPORT"],
    ADDRESS_DISCREPANCY: ["DEED", "PA", "TYPED_REPORT"],
    MAILING_LIST_DISCREPANCY: ["MAILING_LIST", "SEARCH_PACKAGE", "TYPED_REPORT"],
    UPDATE_REPORT_DISCREPANCY: ["UPDATE_REPORT", "SEARCH_PACKAGE", "TYPED_REPORT"],
    LIEN_REGISTRY_DISCREPANCY: ["LIEN_REGISTRY", "SEARCH_PACKAGE", "TYPED_REPORT"],
    COUNTY_DISCREPANCY: ["DEED", "PA", "TYPED_REPORT"],
    ORDER_NUMBER_DISCREPANCY: ["VENDOR_INSTRUCTIONS", "COVER_SHEET", "TYPED_REPORT"],
    UNOFFICIAL_COPY_ISSUE: ["SEARCH_PACKAGE", "VENDOR_INSTRUCTIONS"],
    WATERMARK_COPY_ISSUE: ["SEARCH_PACKAGE", "VENDOR_INSTRUCTIONS"],
    INDEX_SEARCH_DISCREPANCY: ["INDEX", "SEARCH_PACKAGE", "TYPED_REPORT"],
    JUDGMENT_SEARCH_DISCREPANCY: ["COURT_SEARCH", "SEARCH_PACKAGE", "TYPED_REPORT"],
    LENDER_NAME_DISCREPANCY: ["DOT", "SEARCH_PACKAGE", "TYPED_REPORT"],
    ASSIGNMENT_CHAIN_DISCREPANCY: ["ASSIGNMENT", "DOT", "SEARCH_PACKAGE", "TYPED_REPORT"],
    SURVEY_DISCREPANCY: ["SURVEY", "LEGAL_DESCRIPTION", "MAP"],
    TORRENS_CERTIFICATE_DISCREPANCY: ["TORRENS", "SEARCH_PACKAGE", "TYPED_REPORT"],
    COVER_SHEET_DISCREPANCY: ["COVER_SHEET", "SEARCH_PACKAGE", "TYPED_REPORT"],
    MARITAL_STATUS_DISCREPANCY: ["DEED", "SEARCH_PACKAGE", "TYPED_REPORT"],
    TAX_WARRANT_DISCREPANCY: ["TAX", "LIEN", "SEARCH_PACKAGE", "TYPED_REPORT"],
    SUNBIZ_SEARCH_DISCREPANCY: ["SUNBIZ", "DEED", "TYPED_REPORT"],
    CHECKLIST_DISCREPANCY: ["CHECKLIST", "VENDOR_INSTRUCTIONS", "SEARCH_PACKAGE"],
    PROBATE_SEARCH_DISCREPANCY: ["PROBATE", "COURT_SEARCH", "SEARCH_PACKAGE", "TYPED_REPORT"],
    THR_DISCREPANCY: ["THR", "SEARCH_PACKAGE", "TYPED_REPORT"],
    REPORT_COMMENT_DISCREPANCY: ["TYPED_REPORT", "SEARCH_PACKAGE"],
    DOCUMENT_COPY_REQUEST: ["SEARCH_PACKAGE", "TYPED_REPORT"],
    WRONG_DOCUMENT: ["SEARCH_PACKAGE", "TYPED_REPORT"],
    PACER_SEARCH_DISCREPANCY: ["PACER", "TYPED_REPORT"],
    PATRIOT_SEARCH_DISCREPANCY: ["PATRIOT", "TYPED_REPORT"],
    CHAIN_24_MONTH_DISCREPANCY: ["DEED", "SEARCH_PACKAGE", "TYPED_REPORT"],
    FEE_APPROVAL_REQUEST: [], ABSTRACTOR_STATUS: [], NO_REVISION_REQUEST: []
};

/**
 * Returns required document types for a given issue type.
 * 
 * @param {string} issueType 
 * @returns {Array<string>} List of required document types
 */
export function getRequiredDocumentTypes(issueType) {
    const aliases = { TA: "TYPED_REPORT" };
    return [...new Set((DOCUMENT_MAPPINGS[issueType] || [])
        .map(type => aliases[type] || type))];
}
